(require 'ert)
(ert-deftest test-list< ()
  (should (sched-list< nil '(1)))
  (should (sched-list< '(1) '(1 2)))
  (should (sched-list< '(1 1) '(1 2)))
  (should (sched-list< '(1 2) '(2 1)))
  (should (sched-list< '((1 2) 1 2) '((2 1) 1 2)))
  (should (sched-list< '((1) 1 2) '((2) 1 )))
  (should (sched-list< '("abc") '("bcd")))
  (should (sched-list< '("abc") '("abc" 2)))
  (should (sched-list< '(("abc") 1 2) '(("bcd") 1 2)))
  (should (not (sched-list< '("abc") '("abc"))))
  (should (not (sched-list< '("abd") '("abc"))))
  (should (not (sched-list< '(2) '(1))))
  (should (not (sched-list< '(1 2) '(1)))))
